name: marp-to-pages
concurrency: marp-to-pages
on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy images
        run: mkdir build && cp -R ./presentation/assets ./build/assets

      - name: Marp Build html
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: -I presentation -o ./build/index.html --html
        env:
          MARP_USER: root:root

      - name: Marp Build pdf
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: -I presentation -o ./build --pdf --html --allow-local-files
        env:
          MARP_USER: root:root

      - name: Marp Build pptx
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: -I presentation -o ./build --pptx --html --allow-local-files
        env:
          MARP_USER: root:root

      - name: Deploy preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          preview-branch: gh-pages
          umbrella-dir: pr-preview

      - name: Upload artifacts
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            ./build/*.pdf
            ./build/*.pptx

      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/
          clean-exclude: pr-preview/
      

